"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Shape_1 = require("./Shape");
var Cricle_1 = require("./Cricle");
var Rectangle_1 = require("./Rectangle");
var myShape = new Shape_1.Shape(12, 5);
console.log(myShape.getInfo());
var myCricle = new Cricle_1.Cricle(10, 20, 30);
console.log(myCricle.getInfo());
var myRectangle = new Rectangle_1.Rectangle(12, 10, 11, 23);
console.log(myRectangle.getInfo());
